### ISSUE TITLE
Passwords in config file are not being encrypted

### ISSUE THREAD

**Issue by jlignier** [dynamicdan/filesync#10]
The passwords in my app.config.json file remain in plain text format after FileSync is run. The command window displays the 'Configuration: credentials encoded.' but this doesn't seem to be happening.

**Comment by dynamicdan** [comment]
I remember you mentioning this a while back and I tested it out but found no issue. Today I tested it with the default app.config.json file in the filesync dir and I could replicate the issue.

Will investigate.

**Comment by dynamicdan** [comment]
This only happens when NOT running filesync via the command line (eg filesync.command). This is why I missed it because I'm often specifying a "--config" path via the command line. In my case the file was actually still written out but 1 directory up. So it's a relative path issue.

**Comment by jlignier** [comment]
Good stuff mate. I thought it would be an easy fix.
