### ISSUE TITLE
Additional details on notifications

### ISSUE THREAD

**Issue by jlignier** [dynamicdan/filesync#12]
I'd find it very helpful if the sync notifications showed which instance the file got synced to. Even better if it could also show the updateset that the change gets recorded in.

**Comment by dynamicdan** [comment]
For Mac OS You can actually click the notification and it takes you to the record in the browser. There is a limit to how much text can fit in a notification. So some experimentation is needed for optimal visual space usage. 

Maybe squeezing in the update set is a good idea. Want to create a pull request?

**Comment by dynamicdan** [comment]
By default we don't have access to the update set name when making requests. This would therefore be an additional server query per transaction to check the update set in use. Generally the dev needs to know what update set they are working in before they start working. As the update set is only changeable by the user in the instance then the risk of change is minimal. But YES, it would make life easier to know the update set it's just not performant. Perhaps you can provide a performant way to get this info reliably.

In any case, clicking the notification will take you to the instance for more details.
