### ISSUE TITLE
Pulling updates from server

### ISSUE THREAD

**Issue by stegel** [dynamicdan/filesync#13]
Dan,

What an awesome solution! This answers a lot of the pro-code development challenges my team has had. Thank you!

One thing I am wondering, the watcher does a great job detecting changes on the server and telling me that my local version is out of sync. Is there a way to pull the changes to the single file down without doing a full --resync?

**Comment by dynamicdan** [comment]
Thanks! Glad I can help others with the upgrades and enhancements. 

If you want to re-sync just one file then you can empty it and save. FileSync will detect an empty file and treat it as a new file to fill and download from the instance. Just make sure that your editor can properly refresh after the reload. 

Currently there is no instance polling or trigger from the instance to refresh a file.

**Comment by stegel** [comment]
Thanks Dan! This will work for us.
