### ISSUE TITLE
Randomly quitting on me

### ISSUE THREAD

**Issue by stegel** [dynamicdan/filesync#14]
Dan,

Every once in awhile, I'll save a file and not see the growl notification. I switch back to my terminal and see

```
17:25:44 - info: Local has no changes or remote in sync; no need for push/send.

/Users/aj.siegel/Downloads/filesync-master/app/src/file-record.js:128
            callback(true);
            ^
TypeError: undefined is not a function
    at method._saveMeta (/Users/aj.siegel/Downloads/filesync-master/app/src/file-record.js:128:13)
    at /Users/aj.siegel/Downloads/filesync-master/app/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:102:5
    at Object.oncomplete (evalmachine.<anonymous>:297:15)
```

Not sure what my be causing this, what other info can I provide you?

I am running CodeKit in the background handling minification, sass->css.

Thanks

**Comment by dynamicdan** [comment]
Thanks for finding this. You found a minor issue in sync case no. 1 (remote instance version changed to match local file version).
I added a callback so it should be fixed with the next push to the repo.
