### ISSUE TITLE
Similar quitting issues

### ISSUE THREAD

**Issue by stegel** [dynamicdan/filesync#16]
Dan,

I'll start brushing up on my node skills and troubleshooting these myself, but until then, I'll share what I find with you.

```
17:02:02 - debug: -------------------------------------------------------
17:02:02 - info: Received: 
{ table: 'sys_ui_page',
  field: 'html',
  query: 'name=don_cod' }
17:02:02 - debug: Saving meta/hash data for file: /Users/aj.siegel/sites/fs-cod/ui_pages/don_cod.xhtml
17:02:02 - info: Local has no changes or remote in sync; no need for push/send.

/Users/aj.siegel/.Trash/filesync-master/app/src/file-record.js:128
            callback(true);
            ^
TypeError: undefined is not a function
    at method._saveMeta (/Users/aj.siegel/.Trash/filesync-master/app/src/file-record.js:128:13)
    at /Users/aj.siegel/.Trash/filesync-master/app/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:102:5
    at Object.oncomplete (evalmachine.<anonymous>:297:15)
```

**Comment by dynamicdan** [comment]
I just patched this yesterday. Can you please download the latest version and try again?

It was simply that the callback function was not set because it was originally not passed through from the start.

**Comment by dynamicdan** [comment]
Please note, from the error it looks like you're using the version of FileSync in the "Trash". So you are most likely using an old version. Closing issue.

**Comment by stegel** [comment]
Thanks for the catch, not sure why that happened. I had redownloaded your
latest patch, but I missed something

Thanks
