### ISSUE TITLE
unable to open Zip, or Clone project due to directory length

### ISSUE THREAD

**Issue by dnnadmins** [dynamicdan/filesync#24]
For us poor windows users, we are unable to download the project or clone it with GitDesktop- the file paths exceed windows allowances and we get the following errors;

![image](https://cloud.githubusercontent.com/assets/5482467/13530342/e564d2b2-e1ee-11e5-86c1-95068e8e7827.png)

**Comment by dynamicdan** [comment]
This is a known issue on windows systems. For the current version there are not many solutions BUT you're in luck. I'm about to merge in the experimental branch that uses an up-to-date NPM packaging setup. Both the newer NPM install tool and the removal of node_modules from the FileSync repo will mean that you can avoid this windows error.
