### ISSUE TITLE
Download zip is corrupt

### ISSUE THREAD

**Issue by Skrymir01** [dynamicdan/filesync#7]
I am unable to open the zip file after download. Says the file is corrupt.

**Comment by dynamicdan** [comment]
The zip file is generated via github. I have no control over that. I suggest you update your decompression software. Also check for virus checking software that might be tampering with the file. Also check your computer for viruses. Try downloading the zip and expanding it on another computer.

Are you on Mac or Windows?

**Comment by jakubpobiecky** [comment]
Skrymir01 if you are using Windows, I had same issue. Try to unzip it with Winrar. Default windows decompression feature or 7-zip wasn't also working for me.

**Comment by dynamicdan** [comment]
Solution = use Winrar or similar.
@jakubpobiecky thanks.

**Comment by Skrymir01** [comment]
Thanks that worked.
